import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Map from "@/components/maps/maps";
import WhatsAppButton from "@/components/WhatsAppButton";

const inter = Inter({ subsets: ["latin"] });
const mapURL = `${process.env.MAPS_URL}${process.env.MAPS_API_KEY}`;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Map
          googleMapURL={mapURL}
          loadingElement={<div style={{ height: "100%" }} />}
          containerElement={<div style={{ height: "50vh" }} />}
          mapElement={<div style={{ height: "100%" }} />}
        />
        <div>
          <WhatsAppButton phoneNumber="+543816426399" />
        </div>
        <div className="h-[calc(100vh-5rem)]">{children}</div>
      </body>
    </html>
  );
}

// "use client";

// import { Providers } from "../store/providers";
// import "./globals.css";
// import Navbar from "@/components/Navbar/Navbar";
// import Footer from "@/components/footer";
// import { store } from "@/store";
// import { Inter } from "next/font/google";
// import { AuthContextProvider } from "./context/AuthContext";
// const inter = Inter({ subsets: ["latin"] });
// import { ThemeProvider } from "next-themes";

// export const metadata = {
//   title: "Auto Connect",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" class="dark">
//       <body className={inter.className}>
//         <ThemeProvider attribute="class">
//           <AuthContextProvider>
//             <Providers store={store}>
//               <Navbar />
//               {children}
//               <Footer />
//             </Providers>
//           </AuthContextProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
